---

# Vectorized Operations with NumPy

"Vectorization" is an important concept in numeric computing. It refers to the process of operating in entire arrays, in a concise and efficient way. Let's take a look with a couple of examples.

Numpy also refers to _vectorized operations_ as **"array broadcasting"**. 

In [34]:
import numpy as np

In [35]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [36]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

A vectorized operation is any algebraic binary operation you perform on them:

In [37]:
a + b # elementwise operation

array([ 5,  7,  9, 11, 13])

In this case, the operation was performed "element-wise", ie: "vectorized". Let's compare it with a regular for-loop operation:

In [38]:
res = []
for i in range(len(a)):
    res.append(a[i] + b[i])
np.array(res)

array([ 5,  7,  9, 11, 13])

It's much easier to express the operation as `a + b`, instead of explicitly defining the for loop to perform the element-wise sum. This is the difference between _declarative_ and _imperative_ programming.

Finally, compare this to the usage of regular Python lists:

In [39]:
l1 = list(range(5))
l1

[0, 1, 2, 3, 4]

In [40]:
l2 = list(range(5, 10))
l2

[5, 6, 7, 8, 9]

In [41]:
l1 + l2 # sum of lists is not elementwise summing it just adding new elements to new list of sum

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Python lists don't operate "algebraically", the `+` operation is just concatenation.

Generally, array vectorization will always work with arrays of the same size and shape, but it can also work for arrays of different shapes. For example:

In [42]:
A = np.array([
    [0, 0, 0],
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])
A

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [43]:
A.shape

(4, 3)

In [44]:
b = np.array([[1, 2, 3]])
b

array([[1, 2, 3]])

In [45]:
b.shape

(1, 3)

Even though the shapes are different, we can still perform a vectorized operation between `A` and `b`:

In [46]:
A + b # it did elementwise summing for each row in A 

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

This is possible since:

> **The Broadcasting Rule**: Two arrays are compatible for broadcasting if for each _trailing dimension_ (i.e., starting from the end) the axis lengths match or if either of the lengths is 1. Broadcasting is then performed over the missing or length 1 dimensions.

Any operation between arrays not following _The Broadcasting Rule_, will fail with a "broadcast" related error. For example:

In [47]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
b = np.array([5, 5])
b

array([5, 5])

In [49]:
A + b # we can't perform, can't broadcast because the shapes are not compatiable 

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
a = np.arange(0, 6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a + 10 # perform over the whole array, this notion fails for lists.

array([10, 11, 12, 13, 14, 15])

As you can see, the `+ 10` operation was "broadcasted" (or "distributed") among all the elements of the array. This is what we usually do with a list comprehension in pure Python:

In [ ]:
[x + 10 for x in a]

[10, 11, 12, 13, 14, 15]

But this "broadcasting" behavior is default for Numpy. Here are a few other examples:

In [ ]:
a - 5

array([-5, -4, -3, -2, -1,  0])

In [ ]:
a * 3

array([ 0,  3,  6,  9, 12, 15])

## Numpy Boolean Array

This kind of arrays help us to perform some sort of filteration of data that we would use to machine learning.

In [ ]:
a > 2 # it did check element by element, it doesn't work with the lists

array([False, False, False,  True,  True,  True])

In [ ]:
a == 0 

array([ True, False, False, False, False, False])

In [ ]:
c = np.arange(0,20,3)
c

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
c % 2 == 0 # Modular Arithmetic

array([ True, False,  True, False,  True, False,  True])



A common practice is to use the function `np.sum` to count how many elements in the array satisfy a given condition. For example, from our array `a`, how many elements are greater than 2 (`> 2`)? The answer is `3` (elements `3`, `4` and `5`).

In [ ]:
a > 2 # 0 is False and 1 is True, so we can perform sum function.

array([False, False, False,  True,  True,  True])

In [ ]:
np.sum(a > 2)

np.int64(2)


Finally, it's important to note that vectorized operations (algebraic and boolean) with one dimensional arrays will also work for multidimensional arrays:

In [ ]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
A % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [ ]:
A % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])


### Logical Operation

You're probably already familiar with python's logical operators (`and`, `or` and `not`). We'll see now `numpy`'s counterparts. From now on, this table might be useful:
<div align="center">

Python | Numpy
:-----:|:----:
`and` | `&`
`or` | `\|`
`not` | `~`
</div>

In [53]:
a

array([0, 1, 2, 3, 4])

In [ ]:
(a >= 2) & (a < 5)

array([False, False,  True,  True,  True])

In [ ]:
~(a <= 2)

array([False, False, False,  True,  True])

### Logical Operators in Filtering

In [ ]:
a[(a >= 2) & (a < 5)]

array([2, 3, 4])

In [ ]:
a[a >= 3] = 99

In [ ]:
a

array([ 0,  1,  2, 99, 99])