

<div align="center">

#  Python Programming Fundamentals for Deep Learning


**Instructor:** Samaher Alzahrani  
**Date:** 11 May, 2026
</div>

---
 # Class 2: Python Libraries for Machine Learning 
## Topics Covered in This Class:

- Introduction to NumPy
- Linear Algebra with NumPy
- Introduction to Vectorized Operations with NumPy
- Numpy Boolean Array.
- Introduction to Pandas Series
- Introduction to Pandas DataFrames
- Introduction to Plotting with Pandas and Matplotlib.pyplot

<p align="center"> <img src="https://raw.githubusercontent.com/SamaherAlzhrani/Python_Programming_Fundamentals_for_Deep_Learning/main/Samaher_github.png" alt="image" width="200"> </p>



<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Introduction to Numpy

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.


Efficiency in NumPy

One of the primary reasons for NumPy’s performance advantage lies in how it represents and processes data.


In standard Python, everything is treated as an object, including simple numeric values such as integers. These are often referred to as boxed integers, meaning that each value is wrapped in a full Python object. This object carries additional metadata and functionality, which increases memory usage and computational overhead.


In contrast, NumPy arrays are designed to store data using primitive numeric types (such as fixed-size integers and floating-point numbers). These values are stored in contiguous blocks of memory without the extra overhead associated with Python objects.


As a result:

- Memory usage is significantly reduced, since only the raw data is stored
- Computations are faster, as operations are performed directly on the underlying data
- Vectorized operations can be applied efficiently across entire arrays without explicit Python loops


This design enables NumPy to achieve performance levels close to those of lower-level languages while maintaining the usability of Python.

<p align="center"> <img src="https://raw.githubusercontent.com/SamaherAlzhrani/Python_Programming_Fundamentals_for_Deep_Learning/main/Python vs Numpy.jpeg" alt="image" width="800"> </p>

In [1]:
x = 4

In [1]:
import numpy as np

In [2]:
np.random.randn(2, 4)

array([[ 0.42223959,  2.12336061,  0.64892202, -1.13787494],
       [ 0.75173848,  0.31105519, -1.16736934, -0.36774987]])

### Basic Numpy Arrays

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(np.int64(1), np.int64(2))

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])



### Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
c = np.array(['a', 'b', 'c'])

In [19]:
c.dtype # Unicode character long

dtype('<U1')

## Multidimensional Array

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [24]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [25]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [26]:
B.shape

(2, 2, 3)

In [27]:
B.ndim

3

In [28]:
B.size

12

## Indexing and Slicing of Matrices

In [29]:
# Square matrix
A = np.array([
    [1, 2, 3],  # 0
    [4, 5, 6],  # 1
    [7, 8, 9]   # 2
])

In [30]:
A[1]

array([4, 5, 6])

In [31]:
A[1][0]

np.int64(4)

In [32]:
A[1, 0]

np.int64(4)

In [33]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [35]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [36]:
A[:2, 2:]

array([[3],
       [6]])

In [37]:
A[1] = np.array([10, 10, 10])

In [38]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [39]:
A[2] = 9

In [40]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 9,  9,  9]])